### PR TITLE
Update Code to be more PSR-2 compliant

### PR DESCRIPTION
**Pull request by JonasWijne**
see https://www.php-fig.org/psr/psr-2/

### CODE REVIEW

**Comment by regnerisch** [comment]
Am I right you are replacing tabs with spaces?

**Comment by JonasWijne** [comment]
jup, i prefere saying PSR-2 compliant 😛

**Comment by regnerisch** [comment]
As you can see at https://github.com/regnerisch/sets/blob/master/.php_cs#L17 PSR2 it is explicit overwritten by tabs. I'm using tabs because of individual developer tab width setting. But after reading this article http://paul-m-jones.com/post/2012/03/15/on-preferring-spaces-over-tabs-in-php/ I now know why this is not the best choice when it comes to code formatting and I will make it full PSR2 compliant.

**Comment by regnerisch** [comment]
Fix in [v1.0.0](https://github.com/regnerisch/sets/releases/tag/v1.0.0)

**Pull request closed without merging**
